
package Tareas;

import  java.awt.*;
import  java.awt.event.*;
import  javax.swing.*;

public class JFrameVentanaAgenda extends javax.swing.JFrame implements  ActionListener{
        private final  ClsListaDatos  lista ; 
	private Container contenedor  ; 
	private  JLabel  nombreTarea , Materia , fecha , descripcion ;
	private  JTextField  campoNombre , campoMateria , campoFecha , campoDescripcion ;
	private JButton   guardar , eliminar , borrarTareas ; 
	private  JList  listaNombres ; 
	private  DefaultListModel modelo  ; 
	private  JScrollPane  scrollLista ; 
   
        public JFrameVentanaAgenda(){
		lista = new ClsListaDatos(); 
		inicio();
		setTitle("Tareas"); 
		setSize(500,430); 
		setLocationRelativeTo(null); 
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setResizable(false); 
        }     
        private void inicio() {
             contenedor = getContentPane(); 
             contenedor.setLayout(null); 

                
		nombreTarea = new JLabel();
		nombreTarea.setText("Nombre de Tarea:");
		nombreTarea.setBounds(20, 20, 255, 23); 
		campoNombre = new JTextField();
		campoNombre.setBounds(150, 25, 255, 25);

                
		Materia = new JLabel();
                Materia.setText("Materia :"); 
                Materia.setBounds(20, 50, 255, 23);
		campoMateria= new JTextField();
		campoMateria.setBounds(150, 50, 255, 25);

		fecha = new JLabel();
		fecha.setText("Fecha de Entrega:");
		fecha.setBounds(20, 80, 255, 23);  
		campoFecha = new JTextField();
		campoFecha.setBounds(150, 80, 255, 25);

		descripcion = new JLabel();
		descripcion.setText("Descripcion");
		descripcion.setBounds(20, 110, 255, 23); 
		campoDescripcion = new JTextField();
		campoDescripcion.setBounds(150, 110, 255, 25);

		guardar = new JButton();
		guardar.setText("Guardar");
		guardar.setBounds(150, 150, 80, 23); 
		guardar.addActionListener((ActionListener) (this));

		eliminar= new JButton();
		eliminar.setText("Eliminar");
		eliminar.setBounds(155, 280, 80, 23); 
		eliminar.addActionListener((ActionListener) (this));

		borrarTareas= new JButton();
		borrarTareas.setText("Borrar Tareas");
		borrarTareas.setBounds(250, 280, 120, 23);  
		borrarTareas.addActionListener((ActionListener) (this));

		listaNombres = new JList();
		listaNombres.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		modelo = new DefaultListModel();

		scrollLista = new JScrollPane();
		scrollLista.setBounds(150, 190 ,255, 80);
		scrollLista.setViewportView(listaNombres);
		contenedor.add(nombreTarea);
		contenedor.add(campoNombre);
		contenedor.add(Materia);
		contenedor.add(campoMateria);
		contenedor.add(fecha);
		contenedor.add(campoFecha);
		contenedor.add(descripcion);
		contenedor.add(campoDescripcion);
		contenedor.add(guardar);
		contenedor.add(eliminar);
		contenedor.add(borrarTareas);
		contenedor.add(scrollLista);
	}  
    @Override
	public void actionPerformed(ActionEvent evento) {
		if (evento.getSource() == guardar) { 
		  añadirDatos(); 
		}
		if (evento.getSource() == eliminar) { 
			eliminarDatos(listaNombres.getSelectedIndex());
		}

		if (evento.getSource() == borrarTareas) { 
			borraLista(); 
		}
	}
    private void añadirDatos() {
	ClsDatos d;
            d = new ClsDatos(campoNombre.getText(), campoMateria.getText(), campoFecha.getText(), campoDescripcion.getText());
	lista.añadirDatos(d); 
	String elemento = campoNombre.getText() + "-" +	campoMateria.getText() + "-" + campoFecha.getText() + "-" + campoDescripcion.getText();
	modelo.addElement(elemento);
	listaNombres.setModel(modelo);
	campoNombre.setText("");
	campoMateria.setText("");
	campoFecha.setText("");
	campoDescripcion.setText("");
	}
private void eliminarDatos(int indice) {
		if (indice >= 0) { 
                    modelo.removeElementAt(indice);
                    lista.eliminarDatos(indice); 
		} else { 
			JOptionPane.showMessageDialog(null, "Debe seleccionar un elemento","Error", JOptionPane.ERROR_MESSAGE);
		}
	}
private void borraLista() {
		lista.borraLista(); 
		modelo.clear(); 
	}
	 
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */   
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agenda de Tareas");

        jLabel2.setText("Nombre de Tarea:");

        jLabel3.setText("Materia:");

        jLabel4.setText("Fecha de Entrega:");

        jLabel5.setText("Descripcion:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Guardar");

        jButton2.setText("Eliminar");

        jButton3.setText("Borrar Tareas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(114, 114, 114)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVentanaAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameVentanaAgenda().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

   
}
